name: Sorter VPN Aktif

on:
  workflow_dispatch:

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run VPN Sorter
        run: python sorter_vpn.py

      - name: List files for debug
        run: ls -l

      - name: Upload akun aktif
        uses: actions/upload-artifact@v4
        with:
          name: akun_aktif
          path: akun_aktif.txt
