name: Run Accurate Server Checker (MiHoYo Core)

on:
  workflow_dispatch:
    # Jalankan manual
  schedule:
    - cron: '0 */6 * * *'  # Opsional: otomatis tiap 6 jam

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup MiHoYo Core
        run: |
          mkdir -p cores
          wget -O cores/mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.19.13/mihomo-linux-amd64-compatible-v1.19.13.gz
          gunzip -f cores/mihomo.gz
          chmod +x cores/mihomo

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run accurate checker
        run: |
          python checker.py

      - name: Upload active servers
        uses: actions/upload-artifact@v4
        with:
          name: active-servers
          path: results/hasil.txt
